swipe:
  4:
    left:
      command: exec i3 focus left
    right:
      command: exec i3 focus right
    up:
      command: exec i3 focus down
    down:
      command: exec i3 focus up
  3:
    left:
      command: exec i3 workspace prev
    right:
      command: exec i3 workspace next
    up:
      command: exec i3 fullscreen toggle
    down:
      command: exec i3 floating toggle

# threshold:
#   swipe: 0.4
#   pinch: 0.4
# 
# interval:
#   swipe: 0.8
#   pinch: 0.1
