[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
merged = 0
hook_add = '''
let g:polyglot_disabled = ['markdown']
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/dotfiles/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'octol/vim-cpp-enhanced-highlight'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
let g:indentLine_fileTypeExclude = ['help', 'calendar']
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja
'''

[[plugins]]
repo = 'tyru/caw.vim'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = '''
#   source ~/dotfiles/nvim/plugins/coc.rc.vim
# '''

# [[plugins]]
# repo = 'tbodt/deoplete-tabnine'
# build = './install.sh'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
