[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
	source ~/.config/nvim/plugins/quickrun.vim
'''

# [[plugins]]
# repo = 'Shougo/neoinclude.vim'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# hook_source = '''
#   source ~/.config/nvim/plugins/deoplete.vim
# '''

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'neoclide/coc-neco'

# [[plugins]]
# repo = 'ncm2/float-preview.nvim'
# on_source = 'deoplete.nvim'
# if = 'has("nvim")'
# hook_source = '''
#   let g:float_preview#docked = 0
#   let g:float_preview#max_width = 60
#   let g:float_preview#max_height = 20
# '''

# [[plugins]]
# repo = 'Shougo/echodoc.vim'
# on_event = 'CompleteDone'
# hook_source = '''
#   let g:echodoc#type = 'virtual'
#   call echodoc#enable()
# '''

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# depends = ['neosnippet-snippets']
# hook_add = '''
# 	source ~/.config/nvim/plugins/neosnippet.vim
# '''

[[plugins]]
repo = 'itchyny/calendar.vim'
# hook_add = '''
# let g:calendar_google_calendar = 1
# let g:calendar_google_task = 1
# source ~/.cache/calendar.vim/credentials.vim
# '''

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_source = '''
call defx#custom#column('mark', {
      \ 'readonly_icon': '✗',
      \ 'selected_icon': '✓',
      \ })
call defx#custom#column('icon', {
      \ 'directory_icon': '▸',
      \ 'opened_icon': '▾',
      \ 'root_icon': ' ',
      \ })
nnoremap <silent><C-f> :<C-u>Defx <CR>
'''
hook_add = '''
source ~/.config/nvim/plugins/defx.vim
'''
