[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
merged = 0
hook_add = '''
let g:polyglot_disabled = ['markdown']
'''

[[plugins]]
repo = 'rcmdnk/vim-markdown'

# [[plugins]]
# repo = 'neoclide/coc.nvim'
# merged = 0
# rev = 'release'
# hook_add = '''
#   source ~/dotfiles/nvim/plugins/coc.rc.vim
# '''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'octol/vim-cpp-enhanced-highlight'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  if !exists('g:airline_symbols')
    let g:airline_symbols = {}
  endif

  " powerline symbols
  let g:airline_left_sep = ''
  let g:airline_left_alt_sep = ''
  let g:airline_right_sep = ''
  let g:airline_right_alt_sep = ''
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
let g:indentLine_fileTypeExclude = ['help', 'calendar']
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja
'''

[[plugins]]
repo = 'tyru/caw.vim'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
#build = 'bash install.sh'
#hook_add = '''
	#source ~/dotfiles/nvim/plugins/languageclient.vim
#'''

#[[plugins]]
#repo = 'neovim/nvim-lsp'
#hook_add = '''
#lua require'nvim_lsp'.clangd.setup{}
#'''

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = '''
# source ~/dotfiles/nvim/plugins/ale.vim
# '''

# [[plugins]]
# repo = 'tbodt/deoplete-tabnine'
# build = './install.sh'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

# [[plugins]]
# repo = 'tomasr/molokai'

# [[plugins]]
# repo = 'NLKNguyen/papercolor-theme'
