[[plugins]]
repo = 'thinca/vim-quickrun'
hook_source = '''
  source ~/dotfiles/nvim/plugins/quickrun.rc.vim
'''

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
  if filereadable(expand('~/.cache/calendar.vim/credentials.vim', ':h:p'))
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
    source ~/.cache/calendar.vim/credentials.vim
  endif
'''

[[plugins]]
repo = "puremourning/vimspector"
if = 'has("unix")'
on_ft = ["python", "cpp"]
build = "./install_gadget.py --enable-python --enable-c"
hook_add = '''
  source ~/dotfiles/nvim/plugins/vimspector.rc.vim
'''

[[plugins]]
repo = 'jackguo380/vim-lsp-cxx-highlight'
if = 'has("unix")'
on_ft = ["cpp"]

[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'CmdlineEnter'
hook_source = '''
  source ~/dotfiles/nvim/plugins/denite.rc.vim
'''
hook_add = '''
  nnoremap <silent> <Space>g :Denite grep<CR>
  nnoremap <Space>d :Denite 
  nnoremap <Space>b :Denite buffer<CR>
  nnoremap <Space><Space> :Denite file/rec<CR>
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
hook_source = '''
  call defx#custom#column('mark', {
        \ 'readonly_icon': '✗',
        \ 'selected_icon': '✓',
        \ })
  call defx#custom#column('icon', {
        \ 'directory_icon': '▸',
        \ 'opened_icon': '▾',
        \ 'root_icon': ' ',
        \ })
  call defx#custom#option('_', {
        \ 'winwidth': 30,
        \ 'split': 'vertical',
        \ 'direction': 'topleft',
        \ 'resume': 1,
        \ 'listed': 1,
        \ 'columns': 'mark:indent:icons:filename:type:time:size',
        \ 'vertical_preview': 1,
        \ 'floating_preview': 1,
        \ })
  source ~/dotfiles/nvim/plugins/defx.rc.vim
'''
hook_add = '''
  nnoremap <silent><C-f> :<C-u>Defx -buffer-name=`'defx' . tabpagenr()`<CR>
  nmap <silent><Space>f <C-f> :call defx#call_action('cd', [expand('~/dotfiles/nvim')])<CR>
  nmap <silent><Space>w <C-f> :call defx#call_action('cd', [expand('~/work')])<CR>
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'
on_map = {n = '<Plug>(ac-smooth-scroll-'}
hook_add = '''
  let g:ac_smooth_scroll_no_default_key_mappings = 1
  let g:ac_smooth_scroll_du_sleep_time_msec=5
  nmap <silent> <C-d> <Plug>(ac-smooth-scroll-c-d)
  nmap <silent> <C-u> <Plug>(ac-smooth-scroll-c-u)
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = '<Plug>'
hook_add = '''
  let g:clever_f_not_overwrites_standard_mappings = 1
  let g:clever_f_mark_direct = 1
  nmap f <Plug>(clever-f-f)
  xmap f <Plug>(clever-f-f)
  omap f <Plug>(clever-f-f)
  nmap F <Plug>(clever-f-F)
  xmap F <Plug>(clever-f-F)
  omap F <Plug>(clever-f-F)
  nmap t <Plug>(clever-f-t)
  xmap t <Plug>(clever-f-t)
  omap t <Plug>(clever-f-t)
  nmap T <Plug>(clever-f-T)
  xmap T <Plug>(clever-f-T)
  omap T <Plug>(clever-f-T)
'''

[[plugins]]
repo = 'neoclide/coc-denite'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap <Space>s :Denite coc-symbols<CR>
'''

# [[plugins]]
# repo = 'Shougo/neoinclude.vim'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# if = 'has("win32") || has("win64")'
# on_event = 'InsertEnter'
# hook_source = '''
#   source ~/dotfiles/nvim/plugins/deoplete.vim
# '''

# [[plugins]]
# repo = 'Shougo/neco-vim'
# on_ft = 'vim'

# [[plugins]]
# repo = 'neoclide/coc-neco'

# [[plugins]]
# repo = 'ncm2/float-preview.nvim'
# on_source = 'deoplete.nvim'
# if = 'has("nvim")'
# hook_source = '''
#   let g:float_preview#docked = 0
#   let g:float_preview#max_width = 60
#   let g:float_preview#max_height = 20
# '''

# [[plugins]]
# repo = 'Shougo/echodoc.vim'
# on_event = 'CompleteDone'
# hook_source = '''
#   let g:echodoc#type = 'virtual'
#   call echodoc#enable()
# '''

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# depends = ['neosnippet-snippets']
# hook_add = '''
# 	source ~/dotfiles/nvim/plugins/neosnippet.vim
# '''

