hook_add = '''
'''

[ftplugin]

_ = '''
'''

c = '''
"packadd termdebug
'''

go = '''
set expandtab
'''

zig = '''
set tabstop=4
let b:caw_oneline_comment = '//'
'''

markdown = '''
setlocal conceallevel=0
set tabstop=2
set shiftwidth=2
'''

systemverilog = '''
let &commentstring="// %s"
'''
