[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
#build = 'bash install.sh'
#hook_add = '''
	#source ~/.config/nvim/plugins/languageclient.vim
#'''

#[[plugins]]
#repo = 'neovim/nvim-lsp'
#hook_add = '''
#lua require'nvim_lsp'.clangd.setup{}
#'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.vim
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	source ~/.config/nvim/plugins/airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'
