[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  source ~/dotfiles/nvim/plugins/quickrun.rc.vim
'''

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
if has('unix')
  let g:calendar_google_calendar = 1
  let g:calendar_google_task = 1
  if filereadable(expand('~/.cache/calendar.vim/credentials.vim', ':h:p'))
    source ~/.cache/calendar.vim/credentials.vim
  endif
endif
'''

[[plugins]]
repo = "puremourning/vimspector"
if = 'has("unix")'
on_ft = ["python", "cpp"]
build = "./install_gadget.py --enable-python --enable-c"
hook_add = '''
  source ~/dotfiles/nvim/plugins/vimspector.rc.vim
'''

[[plugins]]
repo = 'jackguo380/vim-lsp-cxx-highlight'
if = 'has("unix")'
on_ft = ["cpp"]

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = '''
  source ~/dotfiles/nvim/plugins/denite.rc.vim
  nnoremap <silent> <Space>g :Denite grep<CR>
  nnoremap <Space>d :Denite 
  nnoremap <Space>b :Denite buffer<CR>
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
hook_source = '''
  call defx#custom#column('mark', {
        \ 'readonly_icon': '✗',
        \ 'selected_icon': '✓',
        \ })
  call defx#custom#column('icon', {
        \ 'directory_icon': '▸',
        \ 'opened_icon': '▾',
        \ 'root_icon': ' ',
        \ })
  call defx#custom#option('_', {
        \ 'winwidth': 30,
        \ 'split': 'vertical',
        \ 'direction': 'topleft',
        \ 'resume': 1,
        \ 'listed': 1,
        \ 'columns': 'mark:indent:icons:filename:type:time:size',
        \ 'vertical_preview': 1,
        \ 'floating_preview': 1,
        \ })
'''
hook_add = '''
  source ~/dotfiles/nvim/plugins/defx.rc.vim
  nnoremap <silent><C-f> :<C-u>Defx -buffer-name=`'defx' . tabpagenr()`<CR>
  nmap <silent><Space>f <C-f> :call defx#call_action('cd', [expand('~/dotfiles/nvim')])<CR>
  nmap <silent><Space>w <C-f> :call defx#call_action('cd', [expand('~/work')])<CR>
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

# [[plugins]]
# repo = 'Shougo/neoinclude.vim'

# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# if = 'has("win32") || has("win64")'
# on_event = 'InsertEnter'
# hook_source = '''
#   source ~/dotfiles/nvim/plugins/deoplete.vim
# '''

# [[plugins]]
# repo = 'Shougo/neco-vim'
# on_ft = 'vim'

# [[plugins]]
# repo = 'neoclide/coc-neco'

# [[plugins]]
# repo = 'ncm2/float-preview.nvim'
# on_source = 'deoplete.nvim'
# if = 'has("nvim")'
# hook_source = '''
#   let g:float_preview#docked = 0
#   let g:float_preview#max_width = 60
#   let g:float_preview#max_height = 20
# '''

# [[plugins]]
# repo = 'Shougo/echodoc.vim'
# on_event = 'CompleteDone'
# hook_source = '''
#   let g:echodoc#type = 'virtual'
#   call echodoc#enable()
# '''

# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# depends = ['neosnippet-snippets']
# hook_add = '''
# 	source ~/dotfiles/nvim/plugins/neosnippet.vim
# '''

