[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
	source ~/.config/nvim/plugins/quickrun.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  autocmd InsertLeave * silent! pclose!
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
	source ~/.config/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
let g:calendar_google_calendar = 1
let g:calendar_google_task = 1
source ~/.cache/calendar.vim/credentials.vim
'''

[[plugins]]
repo = 'Matsui54/OxfDictionary.nvim'
hook_add = '''
let g:OxfDictionary#app_id='3fc46c58'
let g:OxfDictionary#app_key='c4603e15e4eb3f7219bd477823507ad6'
'''

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/defx.vim
  nnoremap <silent> <C-f> :<C-u>Defx -split=floating<CR>
'''
hook_source = '''
  call defx#custom#column('mark', {
          \ 'readonly_icon': '✗',
          \ 'selected_icon': '✓',
          \ })
  call defx#custom#column('icon', {
          \ 'directory_icon': '▸',
          \ 'opened_icon': '▾',
          \ 'root_icon': ' ',
          \ })
'''
