[[plugins]]
repo = 'Shougo/denite.nvim'
on_event = 'CmdlineEnter'
hook_source = '''
  source ~/dotfiles/nvim/plugins/denite.rc.vim
'''
hook_add = '''
  nnoremap <Space>d :Denite<Space>
  nnoremap <silent> <Space>g <cmd>Denite grep
      \ -no-empty -auto-action=preview_bat<CR>
  nnoremap <silent> <Space>b <cmd>Denite buffer
      \ -auto-action=preview<CR>
  nnoremap <silent> <Space>a <cmd>Denite file/rec
      \ -auto-action=preview_bat<CR>
  nnoremap <silent> <Space>s <cmd>Denite directory_rec<CR>
  nnoremap <silent> <Space>f <cmd>Denite file/rec:~/dotfiles<CR>
  nnoremap <silent> <Space>h <cmd>Denite help -auto-action=preview<CR>
  nnoremap <silent> <Space>n <cmd>Denite dein<CR>
  nnoremap <silent> <Space>r <cmd>Denite -resume<CR>
  nnoremap <silent> gn <cmd>Denite gina/command<CR>
  cnoremap <expr><silent> <C-t>
      \ "<c-u>Denite command_history -start-filter -input='" . getcmdline() . "'<CR>"
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
hook_add = '''
  function! My_quickrun_redirect() abort
    let input_file = expand('%:h') . '/in.txt'
    if filereadable(input_file)
      execute 'QuickRun <' . input_file
    else
      QuickRun
    endif
  endfunction
'''
hook_source = '''
  source ~/dotfiles/nvim/plugins/quickrun.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete-lsp'

[[plugins]]
repo = 'itchyny/calendar.vim'
on_cmd = 'Calendar'
hook_source = '''
  if filereadable(expand('~/.cache/calendar.vim/credentials.vim', ':h:p'))
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1
    source ~/.cache/calendar.vim/credentials.vim
  endif
  autocmd MyAutoCmd FileType calendar call s:calendar_my_settings()
  function s:calendar_my_settings()
    nnoremap <buffer> <C-j> gT
    nnoremap <buffer> <C-k> gt
  endfunction
'''

[[plugins]]
repo = 'simplenote-vim/simplenote.vim'
on_event = 'CmdlineEnter'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-icons']
hook_source = '''
  source ~/dotfiles/nvim/plugins/defx.rc.vim
'''
hook_add = '''
  nnoremap <silent><C-f> <cmd>Defx -buffer-name=`'defx' . t:defx_index`<CR>
  nmap <silent> <Space>w <C-f>:call defx#call_action('cd', [expand('~/work')])<CR>
  nmap <silent> <Space>p <C-f>:call defx#call_action('cd', [expand('~/.cache/dein/repos/github.com')])<CR>
'''

[[plugins]]
repo = 'Shougo/deol.nvim'
hook_add = '''
  tnoremap <C-\><C-\> <C-\><C-N><cmd>Deol -toggle<CR>
  nnoremap <expr> <C-\><C-\> '<cmd>Deol -toggle -winwidth=' . &columns/2 . ' ' .
  \ ((winnr('$') == 1 && bufname()=='') ? '<CR>' : '-split=vertical<CR>')
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'rhysd/clever-f.vim'
on_map = '<Plug>'
hook_add = '''
  let g:clever_f_not_overwrites_standard_mappings = 1
  let g:clever_f_mark_direct = 1
  let g:clever_f_smart_case = 1
  nmap f <Plug>(clever-f-f)
  xmap f <Plug>(clever-f-f)
  omap f <Plug>(clever-f-f)
  nmap F <Plug>(clever-f-F)
  xmap F <Plug>(clever-f-F)
  omap F <Plug>(clever-f-F)
  nmap t <Plug>(clever-f-t)
  xmap t <Plug>(clever-f-t)
  omap t <Plug>(clever-f-t)
  nmap T <Plug>(clever-f-T)
  xmap T <Plug>(clever-f-T)
  omap T <Plug>(clever-f-T)
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_map = '<plug>(easymotion-'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  let g:EasyMotion_smartcase = 1
  map <Space>j <Plug>(easymotion-j)
  map <Space>k <Plug>(easymotion-k)
  nmap <Space>j <Plug>(easymotion-overwin-line)
  nmap <Space><Space> <Plug>(easymotion-overwin-f2)
  xmap <Space><Space> <Plug>(easymotion-s2)
  omap <Space><Space> <Plug>(easymotion-s2)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
on_map = '<Plug>'
hook_add = '''
  map <silent>sa <Plug>(operator-surround-append)
  map <silent>sd <Plug>(operator-surround-delete)
  map <silent>sr <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'SirVer/ultisnips'
depends = 'vim-snippets'
on_source = 'denite.nvim'
hook_source = '''
  let g:UltiSnipsExpandTrigger='<C-l>'
  let g:UltiSnipsJumpForwardTrigger='<C-j>'
  let g:UltiSnipsJumpBackwardTrigger='<C-k>'
'''
on_event = 'InsertCharPre'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser'
on_cmd = 'OpenBrowserSearch'
hook_add = '''
	nmap gx <Plug>(openbrowser-smart-search)
	vmap gx <Plug>(openbrowser-smart-search)
'''
hook_source = '''
  for cmd in ['wsl-open', 'xdg-open', 'exo-open']
    if executable(cmd)
      let g:openbrowser_browser_commands = [
      \   {'name': cmd,
      \  "args": ["{browser}", "{uri}"]},
      \]
    endif
  endfor
'''

[[plugins]]
repo = 'previm/previm'
on_cmd = 'PrevimOpen'
hook_source = '''
  let g:previm_show_header=0
  if vimrc#is_wsl()
    let g:previm_open_cmd='wsl-open'
  endif
'''
depends = 'open-browser.vim'

[[plugins]]
repo = 'tyru/eskk.vim'
on_map = {ic = '<Plug>'}
hook_add = '''
  imap <C-j>     <Plug>(eskk:toggle)
  cmap <C-j>     <Plug>(eskk:toggle)
'''
hook_source = '''
  let g:eskk#enable_completion=1
  let g:eskk#directory = expand('~/.cache/eskk')
  let g:eskk#start_completion_length=2
  let g:eskk#tab_select_completion=1
  let g:eskk#dictionary = {
        \   'path': expand('~/.cache/skk-jisyo'),
        \   'sorted': 0,
        \   'encoding': 'utf-8',
        \}
  if has('win32') || has('win64')
    let g:eskk#large_dictionary = {
    \	'path': expand('~/AppData/Local/skk/SKK-JISYO.L'),
    \	'sorted': 1,
    \	'encoding': 'euc-jp',
    \}
  endif
'''

[[plugins]]
repo = 'tyru/caw.vim'
on_map = {nx = '<Plug>'}
hook_add = '''
  nmap gc <Plug>(caw:prefix)
  xmap gc <Plug>(caw:prefix)
  nmap gcc <Plug>(caw:hatpos:toggle)
  xmap gcc <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim', 'deoplete-lsp']
on_event = 'InsertEnter'
hook_source = '''
  source ~/dotfiles/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-dictionary'
on_source = 'deoplete.nvim'
hook_source = '''
  call deoplete#custom#source(
  \ 'dictionary', 'min_pattern_length', 4)
  call deoplete#custom#source(
  \ 'dictionary', 'max_candidates', 10)
'''

[[plugins]]
repo = 'Shougo/neco-vim'
on_source = 'context_filetype.vim'

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_add = '''
	let g:echodoc#type = 'floating'
  autocmd MyAutoCmd CmdWinEnter [:>] let g:echodoc#type = 'virtual'
  autocmd MyAutoCmd CmdWinLeave * let g:echodoc#type = 'floating'
'''
hook_source = '''
  call echodoc#enable()
'''

[[plugins]]
repo = 'Shougo/junkfile.vim'
on_source = 'denite.nvim'

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_event = 'CmdlineEnter'
on_source = 'denite.nvim'
hook_add = '''
  nnoremap gs <cmd>Gina status<CR>
'''
hook_source = '''
	call gina#custom#mapping#nmap(
	      \ '/.*', '<C-j>',
	      \ 'gT'
	      \)
	call gina#custom#mapping#nmap(
	      \ '/.*', '<C-k>',
	      \ 'gt'
	      \)
	call gina#custom#mapping#nmap(
	      \ 'status', '<Space>gc',
	      \ ':<C-u>Gina commit<CR>',
	      \ {'noremap': 1, 'silent': 1},
	      \)
'''

[[plugins]]
repo = 't9md/vim-choosewin'
on_source = 'defx.nvim'

# [[plugins]]
# repo = 'sheerun/vim-polyglot'
# on_event = ['BufReadPre', 'BufNewFile']
# hook_add = '''
# let g:polyglot_disabled = ['markdown']
# '''
 
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim") && !vimrc#is_windows()'
on_event = 'BufRead'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
        disable = {},
    },
    refactor = {
      highlight_defintions = {
        enable = true
      },
      smart_rename = {
        enable = true,
        smart_rename = 'grr'
      },
      navigation = {
        enable = true,
        goto_definition = 'gnd',
        list_definitions = 'gnD'
      }
    },
    ensure_installed = 'all'
}
EOF
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufRead'
hook_source = '''
  lua require('lsp_rc')
'''

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_cmd = 'Telescope'
depends = ['popup.nvim', 'plenary.nvim']
hook_source = '''
lua << EOF
require('telescope').setup{
    file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
    grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
    qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,
}
EOF
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_event = 'BufRead'
hook_source = '''
  lua require'colorizer'.setup()
'''

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['zsh', 'sh']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'matsui54/deoplete-google-search'
on_cmd = 'GoogleSearchOpenPrompt'
hook_add = '''
nnoremap <silent><C-p> :GoogleSearchOpenPrompt<CR>
'''

# [[plugins]]
# repo = "puremourning/vimspector"
# if = 'has("unix")'
# on_ft = ["python", "cpp"]
# build = "./install_gadget.py --enable-python --enable-c"
# hook_add = '''
#   source ~/dotfiles/nvim/plugins/vimspector.rc.vim
# '''
