[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_add = '''
  if v:true
    lua require('cmp_rc')
  endif
'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'

[[plugins]]
repo = "rinx/cmp-skkeleton"

[[plugins]]
repo = "uga-rosa/cmp-dictionary"

[[plugins]]
repo = "hrsh7th/cmp-nvim-lua"
