[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
	source ~/nvim/plugins/quickrun.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
	source ~/nvim/plugins/deoplete.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
	source ~/nvim/plugins/neosnippet.vim
'''

[[plugins]]
repo = 'itchyny/calendar.vim'
hook_add = '''
let g:calendar_google_calendar = 1
let g:calendar_google_task = 1
source ~/.cache/calendar.vim/credentials.vim
'''

