[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
if = 'has("unix")'
rev = 'release'
hook_add = '''
  source ~/dotfiles/nvim/plugins/coc.rc.vim
'''

[[plugins]]
repo = 'SirVer/ultisnips'
if = 'has("unix")'
hook_add = '''
  let g:UltiSnipsExpandTrigger='<C-j>'
'''

[[plugins]]
repo = 'honza/vim-snippets'
if = 'has("unix")'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'octol/vim-cpp-enhanced-highlight'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
	source ~/dotfiles/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char_list = ['|', '¦', '┆', '┊']
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'
hook_add = '''
  let g:ac_smooth_scroll_no_default_key_mappings = 1
  let g:ac_smooth_scroll_du_sleep_time_msec=5
  nmap <silent> <C-d> <Plug>(ac-smooth-scroll-c-d)
  nmap <silent> <C-u> <Plug>(ac-smooth-scroll-c-u)
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
set helplang=ja
'''

# [[plugins]]
# repo = 'tpope/vim-commentary'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
#build = 'bash install.sh'
#hook_add = '''
	#source ~/dotfiles/nvim/plugins/languageclient.vim
#'''

#[[plugins]]
#repo = 'neovim/nvim-lsp'
#hook_add = '''
#lua require'nvim_lsp'.clangd.setup{}
#'''

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = '''
# source ~/dotfiles/nvim/plugins/ale.vim
# '''

# [[plugins]]
# repo = 'tbodt/deoplete-tabnine'
# build = './install.sh'

# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'

