[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
    " keymapping
    nnoremap <F5> :wa <bar> :wincmd t <bar> :QuickRun <stdin.txt <CR>
    let g:quickrun_config = {}
    let g:quickrun_config['cpp'] = {
	\  'command': 'clang++',
    \  'cmdopt' : '-std=c++17 -Wall',
    \  'hook/time/enable' : 1
    \}
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tpope/vim-surround'
