#!/usr/bin/env bash

set -eu

# from https://zenn.dev/takakiriy/articles/e65780261dd5e3
while [[ $# -gt 0 ]]; do
    case $1 in
        --wsl)  WSL=true; shift;;
        --laptop) X=true; LAPTOP=true; shift;;
        --desktop) X=true; DESKTOP=true; shift;;
        --pandoc)  PANDOC=true; shift;;
        --tex)  TEX=true; shift;;
        *) echo "[ERROR] Unknown option $1"; exit 1;;
    esac
done

install_paru ()
{
  if [[ ! -x $(which paru) ]]; then
    if [[ ! -d $HOME/.local ]]; then
      mkdir $HOME/.local
    fi
    sudo pacman -S --needed base-devel git
    git clone https://aur.archlinux.org/paru.git $HOME/.local/paru
    pushd $HOME/.local/paru
      makepkg -si
    popd
  fi
}

install_packages ()
{
  PACKAGES=(zsh zsh-syntax-highlighting git-prompt.zsh \
    ripgrep bat fzf fd github-cli bottom htop dust duf rsync \
    nodejs npm go zip deno zig rust julia \
    wget ghq man-db unzip openssh pyenv \
    words skk-jisyo \
    base-devel cmake unzip ninja curl \
    tailscale verilator sshfs vim rclone pacman-contrib ctags \
    reflector parallel \
  )

  if [[ -v X ]]; then
    PACKAGES+=( dolphin ark sddm i3-wm zathura alacritty \
      ttf-hackgen noto-fonts-cjk noto-fonts-emoji \
      xclip fcitx5-mozc fcitx5-im krdc freerdp kdeconnect rofi \
      zathura-pdf-mupdf feh thunderbird picom \
      libreoffice-fresh zoom \
      systemdgenie elisa gwenview spectacle filelight plasma-systemmonitor \
      cups firefox vivaldi xremap-x11-bin \
    )
  fi

  if [[ -v LAPTOP ]]; then
    PACKAGES+=(plasma-meta sddm libinput ruby )
  fi

  if [[ -v DESKTOP ]]; then
    PACKAGES+=( font-manager pavucontrol nvidia nvidia-settings archlinux-wallpaper \
      wallutils libnotify xdg-user-dirs xfce4-notifyd breeze qt5ct \
      lightdm lightdm-gtk-greeter xfce4-screensaver polybar xfce4-power-manager \
    )
  fi

  if [[ -v PANDOC ]]; then
    PACKAGES+=(poppler pandoc-cli pandoc-crossref)
  fi

  if [[ -v TEX ]]; then
    PACKAGES+=(texlive-langjapanese texlive-most biber)
  fi

  paru -S --needed ${PACKAGES[*]}
}

install_dotfiles ()
{
  if [[ ! -d $HOME/dotfiles ]]; then
    git clone https://github.com/matsui54/dotfiles.git ~/dotfiles
  fi
  Dotdir=$HOME/dotfiles $HOME/dotfiles/setup/install_dot
  pushd $HOME/dotfiles
    git remote set-url origin git@github.com:matsui54/dotfiles.git
  popd
}

install_wsl ()
{
  if [[ -v WSL ]]; then
    Dotdir=$HOME/dotfiles $HOME/dotfiles/setup/link_windows_exe
    LocalBin=$HOME/.local/bin
    [ -e $LocalBin/xdg-open ] || ln -sv $HOME/dotfiles/scripts/xdg-open $LocalBin/xdg-open

    set +e
    rg -q "appendWindowsPath = false" /etc/wsl.conf
    if [[ $? -ne 0 ]]; then
      set -e
      echo "Overwrite /etc/wsl.conf"
    cat << EOF | sudo tee /etc/wsl.conf > /dev/null
[interop]
appendWindowsPath = false
EOF
    else
      set -e
    fi
  fi
}

chsh_to_zsh ()
{
  ZSH_BIN=/bin/zsh
  if [[ -x "$ZSH_BIN" && $SHELL != "$ZSH_BIN" ]]; then
    echo "change shell to zsh"
    chsh -s "$ZSH_BIN"
  fi
}

setup_gh ()
{
  echo "check gh auth status"
  set +e
  gh auth status
  if [[ $? -ne 0 ]]; then
    set -e
    if [[ ! -f ~/.ssh/id_ed25519 ]]; then
      ssh-keygen -t ed25519 -C "haru.matu9168@gmail.com"
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_ed25519
    fi
    gh auth login
  else
    set -e
  fi
}

install_pyenv ()
{
  if [[ $(pyenv version-name) == "system" ]]; then
    paru -S --needed base-devel openssl zlib xz tk
    set +e
    pyenv install 3 && pyenv global $(pyenv latest 3)
    set -e
  fi
}

install_nvim ()
{
  if [[ ! -x $(which nvim) ]]; then
    if [[ ! -d "$(ghq root)/github.com/neovim/neovim" ]]; then
      ghq get neovim/neovim
    fi
    if [[ ! -d $HOME/.local/bin ]]; then
      mkdir "$HOME/.local/bin"
    fi
    pushd "$(ghq root)/github.com/neovim/neovim"
      make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/.local/nvim install
      ln -s $HOME/.local/nvim/bin/nvim $HOME/.local/bin/nvim
    popd
  fi
}

install_biz_font ()
{
  if [[ ! -d $HOME/.local/share/fonts ]]; then
    mkdir -p $HOME/.local/share/fonts
  fi
  if [[ ! -f $HOME/.local/share/fonts/BIZUDPGothic-Regular.ttf ]]; then
    curl https://fonts.google.com/download?family=BIZ%20UDPGothic -o /tmp/BIZ_UDPGothic.zip
    unzip /tmp/BIZ_UDPGothic.zip -d $HOME/.local/share/fonts *.ttf
  fi
  if [[ ! -f $HOME/.local/share/fonts/BIZUDPMincho-Regular.ttf ]]; then
    curl https://fonts.google.com/download?family=BIZ%20UDPMincho -o /tmp/BIZ_UDPMincho.zip
    unzip /tmp/BIZ_UDPMincho.zip -d $HOME/.local/share/fonts *.ttf
  fi
  if [[ ! -f $HOME/.local/share/fonts/BIZUDGothic-Regular.ttf ]]; then
    curl https://fonts.google.com/download?family=BIZ%20UDGothic -o /tmp/BIZ_UDGothic.zip
    unzip /tmp/BIZ_UDGothic.zip -d $HOME/.local/share/fonts *.ttf
  fi
  if [[ ! -f $HOME/.local/share/fonts/BIZUDMincho-Regular.ttf ]]; then
    curl https://fonts.google.com/download?family=BIZ%20UDMincho -o /tmp/BIZ_UDMincho.zip
    unzip /tmp/BIZ_UDMincho.zip -d $HOME/.local/share/fonts *.ttf
  fi
}

setup_i3_in_plasma ()
{
  if [[ ! -d $HOME/.config/systemd/user ]]; then
    mkdir -p $HOME/.config/systemd/user
  fi
  if [[ ! -f $HOME/.config/systemd/user/plasma-i3.service ]]; then
    cat << EOF > $HOME/.config/systemd/user/plasma-i3.service
[Unit]
Description=Launch Plasma with i3
Before=plasma-workspace.target

[Service]
ExecStart=/usr/bin/i3
Restart=on-failure

[Install]
WantedBy=plasma-workspace.target
EOF
  fi
  systemctl mask plasma-kwin_x11.service --user
  systemctl enable plasma-i3 --user
  sudo systemctl enable sddm.service
}

setup_fusuma ()
{
  if [[ ! -x ~/.local/share/gem/ruby/3.0.0/bin/fusuma ]]; then
    sudo gpasswd -a $USER input
    newgrp input
    gem install fusuma
    ~/.local/share/gem/ruby/3.0.0/bin/fusuma -d
  fi
}

setup_xremap ()
{
  set +e
  pgrep xremap
  if [[ $? -ne 0 ]]; then
    set -e
    echo "uinput" | sudo tee /etc/modules-load.d/uinput.conf
    echo 'KERNEL=="uinput", GROUP="input", MODE="0660"' | sudo tee /etc/udev/rules.d/99-input.rules
  else
    set -e
  fi
}

enable_service_if_disabled ()
{
  case $(systemctl is-enabled $1) in
      not-found)  echo service $1 not found;;
      disabled) echo enable service $1; systemctl enable $1;;
      enabled) echo service $1 is already enabled;;
      *) echo "[ERROR] enabling service $1"; exit 1;;
  esac
}

start_services ()
{
  enable_service_if_disabled sshd
  enable_service_if_disabled tailscaled
  if [[ -v X ]]; then
    enable_service_if_disabled cups
  fi
  if [[ -v DESKTOP ]]; then
    enable_service_if_disabled lightdm
  fi
  if [[ -v LAPTOP ]]; then
    enable_service_if_disabled bluetooth
  fi
}

setup_desktop_additional ()
{
  if [[ ! -f /etc/X11/xorg.conf.d/00-keyboard.conf ]]; then
    cat << EOF | sudo tee /etc/X11/xorg.conf.d/00-keyboard.conf > /dev/null
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbModel" "pc105"
        Option "XkbOptions" "caps:ctrl_modifier"
        Option "AutoRepeat" "200 20"
EndSection
EOF
  fi
}

install_paru
install_packages
install_dotfiles
install_wsl
chsh_to_zsh
# setup_gh
install_pyenv
install_nvim
if [[ -v X ]]; then
  install_biz_font
fi
if [[ -v LAPTOP ]]; then
  setup_i3_in_plasma
  setup_fusuma
  setup_xremap
fi
start_services
if [[ -v DESKTOP ]]; then
  setup_desktop_additional
fi
echo "done"
