#!/usr/bin/env bash

set -eu

# from https://zenn.dev/takakiriy/articles/e65780261dd5e3
while [[ $# -gt 0 ]]; do
    case $1 in
        --wsl)  WSL=true; shift;;
        --desktop)  DESKTOP=true; shift;;
        --pandoc)  PANDOC=true; shift;;
        --tex)  TEX=true; shift;;
        *) echo "[ERROR] Unknown option $1"; exit 1;;
    esac
done

install_paru ()
{
  if [[ ! -x $(which paru) ]]; then
    if [[ ! -d $HOME/.local ]]; then
      mkdir $HOME/.local
    fi
    sudo pacman -S --needed base-devel git
    git clone https://aur.archlinux.org/paru.git $HOME/.local/paru
    pushd $HOME/.local/paru
      makepkg -si
    popd
  fi
}

install_packages ()
{
  PACKAGES=(zsh zsh-syntax-highlighting git-prompt.zsh \
    ripgrep bat fzf fd github-cli bottom htop dust duf rsync \
    nodejs npm go zip deno zig rust julia \
    wget ghq man-db unzip openssh pyenv \
    words skk-jisyo \
    base-devel cmake unzip ninja curl )

  if [[ -v DESKTOP ]]; then
    PACKAGES+=(plasma-meta dolphin ark sddm i3-wm zathura alacritty \
      ttf-hackgen noto-fonts-cjk noto-fonts-emoji \
      xclip fcitx5-mozc fcitx5-im krdc freerdp kdeconnect rofi xremap-x11-bin \
      zathura-pdf-mupdf feh thunderbird libinput ruby picom \
    )
  fi

  if [[ -v PANDOC ]]; then
    PACKAGES+=(poppler pandoc-cli pandoc-crossref)
  fi

  if [[ -v TEX ]]; then
    PACKAGES+=(texlive-langjapanese texlive-most biber)
  fi

  paru -S --needed ${PACKAGES[*]}
}

install_dotfiles ()
{
  if [[ ! -d $HOME/dotfiles ]]; then
    git clone https://github.com/matsui54/dotfiles.git ~/dotfiles
  fi
  Dotdir=$HOME/dotfiles $HOME/dotfiles/setup/install_dot
  pushd $HOME/dotfiles
    git remote set-url origin git@github.com:matsui54/dotfiles.git
  popd
}

install_wsl ()
{
  if [[ -v WSL ]]; then
    Dotdir=$HOME/dotfiles $HOME/dotfiles/setup/link_windows_exe
    LocalBin=$HOME/.local/bin
    [ -e $LocalBin/xdg-open ] || ln -sv $HOME/dotfiles/scripts/xdg-open $LocalBin/xdg-open

    set +e
    rg -q "appendWindowsPath = false" /etc/wsl.conf
    if [[ $? -ne 0 ]]; then
      set -e
      echo "Overwrite /etc/wsl.conf"
    cat << EOF | sudo tee /etc/wsl.conf > /dev/null
[interop]
appendWindowsPath = false
EOF
    else
      set -e
    fi
  fi
}

chsh_to_zsh ()
{
  ZSH_BIN=/bin/zsh
  if [[ -x "$ZSH_BIN" && $SHELL != "$ZSH_BIN" ]]; then
    echo "change shell to zsh"
    chsh -s "$ZSH_BIN"
  fi
}

setup_gh ()
{
  echo "check gh auth status"
  set +e
  gh auth status
  if [[ $? -ne 0 ]]; then
    set -e
    if [[ ! -f ~/.ssh/id_ed25519 ]]; then
      ssh-keygen -t ed25519 -C "haru.matu9168@gmail.com"
      eval "$(ssh-agent -s)"
      ssh-add ~/.ssh/id_ed25519
    fi
    gh auth login
  else
    set -e
  fi
}

install_pyenv ()
{
  if [[ $(pyenv version-name) == "system" ]]; then
    paru -S --needed base-devel openssl zlib xz tk
    set +e
    pyenv install 3 && pyenv global $(pyenv latest 3)
    set -e
  fi
}

install_nvim ()
{
  if [[ ! -x $(which nvim) ]]; then
    if [[ ! -d "$(ghq root)/github.com/neovim/neovim" ]]; then
      ghq get neovim/neovim
    fi
    if [[ ! -d $HOME/.local/bin ]]; then
      mkdir "$HOME/.local/bin"
    fi
    pushd "$(ghq root)/github.com/neovim/neovim"
      make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/.local/nvim install
      ln -s $HOME/.local/nvim/bin/nvim $HOME/.local/bin/nvim
    popd
  fi
}

install_biz_font ()
{
  curl https://fonts.google.com/download?family=BIZ%20UDPGothic -o /tmp/BIZ_UDPGothic.zip
  curl https://fonts.google.com/download?family=BIZ%20UDPMincho -o /tmp/BIZ_UDPMincho.zip
  curl https://fonts.google.com/download?family=BIZ%20UDGothic -o /tmp/BIZ_UDGothic.zip
  curl https://fonts.google.com/download?family=BIZ%20UDMincho -o /tmp/BIZ_UDMincho.zip
  if [[ ! -d $HOME/.local/share/fonts ]]; then
    mkdir -p $HOME/.local/share/fonts
  fi
  unzip /tmp/BIZ_UDPGothic.zip -d $HOME/.local/share/fonts *.ttf
  unzip /tmp/BIZ_UDPMincho.zip -d $HOME/.local/share/fonts *.ttf
  unzip /tmp/BIZ_UDGothic.zip -d $HOME/.local/share/fonts *.ttf
  unzip /tmp/BIZ_UDMincho.zip -d $HOME/.local/share/fonts *.ttf
}

setup_i3_in_plasma ()
{
  if [[ ! -d $HOME/.config/systemd/user ]]; then
    mkdir -p $HOME/.config/systemd/user
  fi
  if [[ ! -f $HOME/.config/systemd/user/plasma-i3.service ]]; then
    cat << EOF > $HOME/.config/systemd/user/plasma-i3.service
[Unit]
Description=Launch Plasma with i3
Before=plasma-workspace.target

[Service]
ExecStart=/usr/bin/i3
Restart=on-failure

[Install]
WantedBy=plasma-workspace.target
EOF
  fi
  systemctl mask plasma-kwin_x11.service --user
  systemctl enable plasma-i3 --user
  sudo systemctl enable sddm.service
}

setup_for_laptop ()
{
  systemctl enable bluetooth.service
  systemctl start bluetooth.service
  if [[ ! -x ~/.local/share/gem/ruby/3.0.0/bin/fusuma ]]; then
    sudo gpasswd -a $USER input
    newgrp input
    gem install fusuma
    ~/.local/share/gem/ruby/3.0.0/bin/fusuma -d
  fi
  set +e
  pgrep xremap
  if [[ $? -ne 0 ]]; then
    set -e
    echo "uinput" | sudo tee /etc/modules-load.d/uinput.conf
    echo 'KERNEL=="uinput", GROUP="input", MODE="0660"' | sudo tee /etc/udev/rules.d/99-input.rules
  else
    set -e
  fi
}

install_paru
install_packages
install_dotfiles
install_wsl
chsh_to_zsh
setup_gh
install_pyenv
install_nvim
install_biz_font
setup_i3_in_plasma
setup_for_laptop
echo "done"
