#!/bin/bash

set -eu

if [[ ! -x $(which paru) ]]; then
  if [[ ! -d $HOME/.local ]]; then
    mkdir $HOME/.local
  fi
  sudo pacman -S --needed base-devel git
  git clone https://aur.archlinux.org/paru.git $HOME/.local/paru
  pushd $HOME/.local/paru
    makepkg -si
  popd
fi

paru -S --needed zsh zsh-syntax-highlighting git-prompt.zsh \
  ripgrep bat fzf fd github-cli bottom htop dust duf \
  nodejs npm go zip deno zig rust julia \
  wget ghq man-db unzip openssh pyenv \
  neovim-nightly-bin words skk-jisyo words \
  poppler pandoc-cli pandoc-crossref \
  texlive-langjapanese texlive-most biber

if [[ ! -d $HOME/dotfiles ]]; then
  git clone https://github.com/matsui54/dotfiles.git ~/dotfiles
fi
Dotdir=$HOME/dotfiles $HOME/dotfiles/setup/install_dot
Dotdir=$HOME/dotfiles $HOME/dotfiles/setup/link_windows_exe

if [[ -x "/usr/bin/zsh" && $SHELL != "/usr/bin/zsh" ]]; then
  echo "change shell to zsh"
  chsh -s /usr/bin/zsh
fi

echo "check gh auth status"
set +e
gh auth status
if [[ $? -ne 0 ]]; then
  set -e
  if [[ ! -f ~/.ssh/id_ed25519 ]]; then
    ssh-keygen -t ed25519 -C "haru.matu9168@gmail.com"
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_ed25519
  fi
  gh auth login
else
  set -e
fi

pushd $HOME/dotfiles
  git remote set-url origin git@github.com:matsui54/dotfiles.git
popd

if [[ $(pyenv version-name) == "system" ]]; then
  paru -S --needed base-devel openssl zlib xz tk
  set +e
  pyenv install 3 && pyenv global $(pyenv latest 3)
  set -e
fi

set +e
rg -q "appendWindowsPath = false" /etc/wsl.conf
if [[ $? -ne 0 ]]; then
  set -e
  echo "Overwrite /etc/wsl.conf"
  cat << EOF | sudo tee /etc/wsl.conf > /dev/null
[interop]
appendWindowsPath = false
EOF
else
  set -e
fi
