#!/bin/bash -eu

echo "install files in $Dotdir"

for f in .vimrc .gitconfig .latexmkrc .zshenv .zshrc
do
  if [[ ! -e $HOME/$f ]]; then
    ln -sv "$Dotdir/$f" "$HOME/$f"
  fi
done

if [[ ! -d $HOME/.config ]]; then
  mkdir "$HOME/.config"
fi

if [[ ! -d $HOME/.config/nvim ]]; then
  ln -sv "$Dotdir/nvim" "$HOME/.config/nvim"
fi

while read -r p; do
  if [[ ! -e $HOME/.config/$p ]]; then
    ln -sv "$Dotdir/.config/$p" "$HOME/.config/$p"
  fi
done < <(find "$Dotdir/.config" -mindepth 1 -maxdepth 1 -exec basename {} \;)
