nmap <F3> :VimspectorReset<CR>
nmap <F4> <Plug>VimspectorRestart
nmap <F5> <Plug>VimspectorContinue
nmap <F6> <Plug>VimspectorToggleBreakpoint
nmap <Leader><F6> <Plug>VimspectorToggleConditionalBreakpoint
nmap <F7> <Plug>VimspectorStepOver
nmap <F8> <Plug>VimspectorStepInto
nmap <F9> <Plug>VimspectorStepOut
nmap <F10> <Plug>VimspectorAddFunctionBreakpoint
